name: finance # You can change this to your environment name
channels:
  - conda-forge
  - defaults
dependencies:
  # Core Python version
  - python=3.12   

  # Core data and modeling libraries from conda-forge
  - pandas>=2.0.0
  - numpy>=1.24.0
  - scipy>=1.10.0
  - pydantic>=2.0
  - pyyaml>=6.0
  - yfinance>=0.2.61
  - curl_cffi>=0.6            # yfinance backend
  - brfinance>=0.0.9          # NEW
  - requests>=2.30.0
  - arch-py>=5.3.0
  - statsmodels>=0.14.0
  - scikit-learn>=1.3.0
  - cvxpy>=1.3.0
  - osqp>=0.6.0
  - holidays>=0.30

  # Development and notebook tools
  - jupyterlab>=4.0.0
  - notebook>=7.0.0
  - pytest>=7.4.0
  - ruff>=0.1.0
  - dask>=2023.9.0
  - joblib>=1.3.0

  # Reporting and visualization
  - matplotlib>=3.7.0
  - plotly>=5.15.0
  - bokeh>=3.2.0
  - nbconvert>=7.8.0
  - openpyxl>=3.1.0
  - python-docx>=1.1.0

  # Pip-specific packages
  - pip
  - pip:
      # This line is crucial: it installs your project's source code
      # in "editable" mode, so changes to your .py files are
      # immediately available without reinstalling.
      - -e .